### ISSUE TITLE
It's not possible to see all the posts

### ISSUE THREAD

**Issue by arturoherrero** [gemcfadyen/georginam.com#1]
We cannot see all the posts. How about a pagination, infinite scroll or something similar?

BTW, do you know more blogs of 8th Light Apprenticeship guys?

**Comment by gemcfadyen** [comment]
Hi Arturo, I have removed the limit of 50 posts, so now all the posts are viewable.

The official 8th light blog is at: https://blog.8thlight.com  which has some great articles on. Most of us also have a personal blog. The blogs of the current apprentices in London are featured on this gist: https://gist.github.com/Maikon/616142912ef431c28325

Enjoy!
